erik1110/SuperHandy-frontend

middleware/unmatch.global.js
feature: unmatch route to root index
=> feature: unmatch route to root index

pages/index.vue
[T5900002](feature: git train)
=> feature: git train

components/Breadcrumbs.vue, layouts/default.vue, services/siteConfig.js
=> Add : breadcrumb

app.vue, components/Footer.vue, layouts/clean.vue, pages/auth/login.vue
=> Add:footer,clean layout

components/Auth/SheetWrapper.vue, components/Navbar.vue, pages/auth/login.vue, pages/auth/signup.vue, pages/find-tasks/[view].vue, plugins/vuetify.js
Add: vuetify color theme＆測試Merge訊息
=> Add: vuetify color theme

components/Auth/SheetWrapper.vue, composables/spUtility.js, composables/useHttp_v2.js, pages/auth/signup.vue, pages/index.vue, services/apis/home.js
- 基於原本useHttp優化，有放範例（services apis 資料夾 getCompletedCases），原版的先保留，待討論完畢看如何調整
- 把原來的spUtility放上去，等等拉branch整合useFormUtility
- 調整SheetWrapper 高度
=> Add: useHttp_v2 req

pages/index.vue
=> Fix: paralax bug

components/Navbar.vue
quick fixed little bug : logo css
=> Fix: clear logo css

components/Home/SecWrapper.vue, pages/index.vue
=> Add: update index spacing

components/Home/SecWrapper.vue, pages/index.vue
=> Fix: index bg colors

assets/css/tailwind.css, components/Dialog/Modal.vue, components/Home/HelperCard.vue, components/Home/SecWrapper.vue, components/Home/UserModal.vue, components/SpStarRating.vue, components/UserCard.vue, package-lock.json, package.json, pages/index.vue, plugins/rating.client.js, pnpm-lock.yaml, tailwind.config.js
- 首頁最優秀幫手 carousel
- 幫手卡片dialog
- 新增 starRating 套件
=> Add: carousel

nuxt.config.js, package-lock.json, package.json, tailwind.config.js
=> Fixed: remove @nextjs/google-fonts

app.vue, assets/css/tailwind.css, components/FindTasks/Filters.vue, components/Home/HelperCard.vue, components/UserCard.vue, package-lock.json, package.json, pages/index.vue, plugins/rating.client.js
vue-star-rating 會有[Violation]Added non-passive event listener to a scroll-blocking 'touchstart' event.的問題
原本用default-passive-events套件可解決，但此套件強制所有event都變成passive，導致vuetify select無法使用，因此決定刪除 vue-star-rating 套件，改用vuetify rating
=> Fixed: Event Passive bugs

assets/css/tailwind.css, components/FindTasks/Filters.vue
=> Add: filters form

components/FindTasks/Card.vue, components/FindTasks/Filters.vue, components/FindTasks/Highlight.vue, components/FindTasks/HighlightCard.vue, components/Home/HelperCard.vue, composables/useMoment.js, pages/find-tasks/index.vue, pages/find-tasks/index/list.vue, plugins/moment.js, plugins/vuetify.js, services/apis/findTasks.js
- 找任務相關API 放入services/api file
- 串接推薦任務api
- 新增推薦任務ui
- 串接 找任務列表
=> Add: highlight api & get list view api

components/FindTasks/Highlight.vue, composables/useMoment.js, plugins/moment.client.js
=> Fixed: take off loop from swiper

components/FindTasks/Tabs.vue, pages/find-tasks/index/list.vue, stores/storeFindTasks.js
=> Add: total tasks

pages/find-tasks/index/map.vue
=> Fixd: modified zoomUpdated

components/FindTasks/Filters.vue, components/FindTasks/Highlight.vue, stores/storeFindTasks.js
- highlight換真的資料測試
- fixd: 找任務服務類型篩選
=> Add: turn fake highlight data to real

pages/find-tasks/index/map.vue
Other: test getData at get position
=> Other: test getData at get position

components/Chat/Modal.vue, components/Chat/Room.vue, components/Chat/RoomCard.vue
=> Add: mobile text modified

components/PostTask/Form.vue
=> Fix: show delete message

components/Chat/Room.vue, stores/storeChatBox.js
=> Add: chat room loading

stores/storeChatBox.js
auto close chat modal when change route
=> Add: auto close chat modal when change route

components/Chat/RoomCard.vue, components/FindTasks/Filters.vue, components/FindTasks/Highlight.vue, components/Navbar.vue, composables/useHttp.js, pages/account/index.vue, pages/account/points/exchange.vue, pages/account/points/history.vue, pages/auth/login.vue, pages/auth/signup.vue, pages/auth/verify-email.vue, pages/find-tasks/index/list.vue, pages/find-tasks/index/map.vue, pages/index.vue, stores/storeChatBox.js, stores/storeFindTasks.js
=> Fixed: clear log

components/Home/CommentCard.vue, components/Home/CompletedCard.vue, components/Home/HelperCard.vue, components/UserCard.vue
- 假圖改成api回傳的圖片
- 完成任務RWD
- 完成任務卡片地址顯示
=> Fixed: home bugs

stores/storeChatBox.js
updateChatList 誤刪 renewIdx ，重新加回
=> Fixed: chat add renewIdx

components/Home/IntroCard.vue, components/Home/Steper.vue, static/home.json
=> Fixed: homepage sec2 intro

components/Notifications.vue
=> Fix: navigateTo no reload
